spring.application.name=demo

mybatis.configuration.map-underscore-to-camel-case=true

# Postgres接続情報を記入
spring.datasource.url=jdbc:postgresql://localhost:5432/fullness_ec
# spring.datasource.url=jdbc:postgresql://exercise-database.cx28wmyqcawc.ap-northeast-1.rds.amazonaws.com:5432/exercise
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.type-aliases-package=com.example.fullness.stationary.entity

app.upload.dir=/var/app/uploads

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
